### PR TITLE
Export FORM_DEFAULTS_FIELD to fix #227

### LINKED ISSUE #227: [Bug]: Cannot find name 'FORM_DEFAULTS_FIELD' in index.d.ts
### Which packages are impacted?

- [X] `remix-validated-form`
- [ ] `@remix-validated-form/with-zod`
- [ ] `@remix-validated-form/with-yup`
- [ ] `zod-form-data`

### What version of these packages are you using?

- `remix-validated-form`: 4.6.7

### Please provide a link to a minimal reproduction of the issue.

https://github.com/haines/remix-validated-form-ts-error

### Steps to Reproduce the Bug or Issue

1. Add `remix-validated-form` to a Remix app
2. Run `npm run typecheck`
3. See an error

```
node_modules/remix-validated-form/dist/index.d.ts:165:33 - error TS2304: Cannot find name 'FORM_DEFAULTS_FIELD'.

165     [formDefaultsKey: `${typeof FORM_DEFAULTS_FIELD}_${string}`]: any;
```

### Expected behavior

Type-checking succeeds

### Screenshots or Videos

_No response_

### Platform

N/A

### Additional context

This appears to have been introduced in https://github.com/airjp73/remix-validated-form/pull/222

### PR DESCRIPTION
**Pull request by stephenwade**
Since https://github.com/egoist/tsup/issues/813 has been ignored, this PR fixes the missing type issue on our side by exporting the missing type.

Fixes #227.

### CODE REVIEW

**Comment by airjp73** [comment]
Thanks!
