### ISSUE TITLE
[Bug]: Cannot find name 'FORM_DEFAULTS_FIELD' in index.d.ts

### ISSUE THREAD

**Issue by haines** [airjp73/remix-validated-form#227]
### Which packages are impacted?

- [X] `remix-validated-form`
- [ ] `@remix-validated-form/with-zod`
- [ ] `@remix-validated-form/with-yup`
- [ ] `zod-form-data`

### What version of these packages are you using?

- `remix-validated-form`: 4.6.7

### Please provide a link to a minimal reproduction of the issue.

https://github.com/haines/remix-validated-form-ts-error

### Steps to Reproduce the Bug or Issue

1. Add `remix-validated-form` to a Remix app
2. Run `npm run typecheck`
3. See an error

```
node_modules/remix-validated-form/dist/index.d.ts:165:33 - error TS2304: Cannot find name 'FORM_DEFAULTS_FIELD'.

165     [formDefaultsKey: `${typeof FORM_DEFAULTS_FIELD}_${string}`]: any;
```

### Expected behavior

Type-checking succeeds

### Platform

N/A

### Additional context

This appears to have been introduced in https://github.com/airjp73/remix-validated-form/pull/222

**Comment by airjp73** [comment]
I was able to trace this issue back to `tsup` and opened an issue [here](https://github.com/egoist/tsup/issues/813). If we don't get a response, we can fix it by exporting the type.

Fortunately, I don't think this type is very critical. You should be able to set `"skipLibCheck": true` in your tsconfig and go about your day :).

**Comment by haines** [comment]
Nice find, thanks for investigating!
