### ISSUE TITLE
[Bug]: @remix-validated-form/with-zod does not compile with typescript 4.8.x

### ISSUE THREAD

**Issue by fnimick** [airjp73/remix-validated-form#173]
### Which packages are impacted?

- [ ] `remix-validated-form`
- [X] `@remix-validated-form/with-zod`
- [ ] `@remix-validated-form/with-yup`
- [ ] `zod-form-data`

### What version of these packages are you using?

- `@remix-validated-form/with-zod: 2.0.1`
- `zod: 3.19.1`

### Please provide a link to a minimal reproduction of the issue.

(unable to reproduce on codesandbox - compiling hangs)

### Steps to Reproduce the Bug or Issue

Compilation error: `@remix-validated-form/with-zod/build/index.d.ts(6,62): error TS2344: Type 'U' does not satisfy the constraint 'ZodTypeDef'.`

### Expected behavior

Should compile with no errors.

### Platform

OS: [node on osx]
Browser: [none]
Version: [none]
